### ISSUE TITLE
Log4jALA support for Log4j2

### ISSUE THREAD

**Issue by soma-data-engineering** [ptv-logistics/Log4jALA#1]
Can we have Log4jALA with Log4j2 as Log4j1.x is outdated and if we want to use it for dropwizard as external logging, it works well with  Log4j2, but not with log4j 1.x.

Currently we want to use "dropwizard with no logback and include Log4jALA appender using log4j".

**Comment by soma-data-engineering** [comment]
@moberacker
Do you have ETA for Log4jALA with Log4j2 ??

**Comment by moberacker** [comment]
not at the moment
